version: '3.4'

services:
  db:
    container_name: db
    image: postgis/postgis:14-3.2
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=cinema
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data
    command: postgres -c stats_temp_directory=/tmp
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - '5050:80'
    restart: always
    volumes:
      - ./db/pgadmin:/root/.pgadmin
  server:
    container_name: server
    build:
      context: server
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=cinema
      - POSTGRES_HOST=db
    restart: always
    depends_on:
      - db
